{ pkgs }: {
  deps = [
    pkgs.vimPlugins.neoinclude-vim
    pkgs.linuxPackages_4_19_hardened.new-lg4ff
    pkgs.vimPlugins.neotest-dart
    pkgs.haskellPackages.newline
    pkgs.or1k-newlib
    pkgs.python312Packages.nexia
    pkgs.luajitPackages.neotest
    pkgs.newt
    pkgs.haskellPackages.neononempty
    pkgs.haskellPackages.needle
    pkgs.linuxPackages-libre.new-lg4ff
    pkgs.neovide
    pkgs.nest
    pkgs.linuxPackages_6_1_hardened.new-lg4ff
    pkgs.nerdctl
    pkgs.nexuiz
    pkgs.ne
    pkgs.netassert
    pkgs.sbclPackages.net_dot_didierverna_dot_declt_dot_setup
    pkgs.haskellPackages.network-multicast
    pkgs.linuxPackages_6_1_hardened.netatop
    pkgs.haskellPackages.network-simple-ws
    pkgs.azure-cli-extensions.networkcloud
    pkgs.haskellPackages.network-ip
    pkgs.haskellPackages.netlib-carray
    pkgs.networkaudiod
    pkgs.haskellPackages.network-byte-order
    pkgs.linuxPackages_5_10_hardened.netatop
    pkgs.sbclPackages.network-addresses
    pkgs.haskellPackages.netlink
    pkgs.sbclPackages.net_dot_didierverna_dot_focus_dot_demos_dot_quotation
    pkgs.haskellPackages.net-spider-rpl
    pkgs.python311Packages.nethsm
    pkgs.haskellPackages.network_3_2_0_0
    pkgs.python312Packages.netcdf4
    pkgs.haskellPackages.net-spider-cli
    pkgs.haskellPackages.network-uri-json
    pkgs.linuxPackages.netatop
    pkgs.haskellPackages.network-house
    pkgs.haskellPackages.network-pgi
    pkgs.netmaker-full
    pkgs.haskellPackages.network-dbus
    pkgs.sbclPackages.net_dot_didierverna_dot_focus_dot_setup
    pkgs.unixtools.netstat
    pkgs.haskellPackages.network-transport-zeromq
    pkgs.python312Packages.netdata
    pkgs.haskellPackages.net-mqtt
    pkgs.postgresql
    pkgs.google-cloud-sdk
    pkgs.google-cloud-sdk-gce
    pkgs.python312Packages.python-etcd
    pkgs.python311Packages.python-prctl
    pkgs.vimPlugins.python-mode
    pkgs.python311Packages.python-gvm
    pkgs.python311Packages.python-ptrace
    pkgs.python311Packages.debianbts
    pkgs.python311Packages.python-secp256k1-cardano
    pkgs.python311Packages.python-miio
    pkgs.python312Packages.python-docx
    pkgs.python311Packages.jsonnet
    pkgs.python311Packages.recursive-pth-loader
    pkgs.python311Packages.python-idzip
    pkgs.python312Packages.python-mimeparse
    pkgs.python312Packages.gflags
    pkgs.python311Packages.python-gammu
    pkgs.python311Packages.python-dateutil
    pkgs.python312Packages.python-songpal
    pkgs.python312Packages.python-simple-hipchat
    pkgs.python312Packages.debianbts
    pkgs.python312Packages.python-box
    pkgs.python311Packages.pythonNamespacesHook
    pkgs.python311Packages.consul
    pkgs.python311Packages.python-nvd3
    pkgs.python312Packages.python-packer
    pkgs.python27Full
    pkgs.python27
    pkgs.python2Full
    pkgs.emacsPackages.python
    pkgs.python2
    pkgs.emacsPackages.pip-requirements
    pkgs.haskellPackages.pipeclip
    pkgs.haskellPackages.pipes-vector
    pkgs.python311Packages.pipBuildHook
    pkgs.python312Packages.pip-tools
    pkgs.python312Packages.pipx
    pkgs.python311Packages.pipe
    pkgs.haskellPackages.pipes-websockets
    pkgs.haskellPackages.pipes-random
    pkgs.haskellPackages.pipes-binary
    pkgs.haskellPackages.pipes-zeromq4
    pkgs.haskellPackages.pipes-brotli
    pkgs.haskellPackages.pipes-concurrency
    pkgs.haskellPackages.pipes-kafka
    pkgs.haskellPackages.pipes-protolude
    pkgs.piping-server-rust
    pkgs.haskellPackages.pipes-extras
    pkgs.piper-train
    pkgs.pipework
    pkgs.python311Packages.pipx
    pkgs.haskellPackages.pipes-s3
    pkgs.python312Packages.pip-system-certs
    pkgs.haskellPackages.pipes-cliff
    pkgs.python312Packages.pipetools
    pkgs.haskellPackages.pipes-text
    pkgs.pipectl
    pkgs.haskellPackages.pipes-safe
    pkgs.python312Packages.pip
    pkgs.python311Packages.pip
    pkgs.rPackages.NPMLEcmprsk
    pkgs.rPackages.npmr
    pkgs.zsh-better-npm-completion
    pkgs.nss_pam_ldapd
    pkgs.haskellPackages.nth-prime
    pkgs.emacsPackages.newlisp-mode
    pkgs.emacsPackages.newspeak-mode
    pkgs.rPackages.nparMD
    pkgs.haskellPackages.nixfromnpm
    pkgs.rPackages.NPMVCP
    pkgs.rPackages.NPMLEmix
    pkgs.haskellPackages.g-npm
    pkgs.rPackages.npmv
    pkgs.rPackages.npmlda
    pkgs.rPackages.npmlreg
    pkgs.npm-lockfile-fix
    pkgs.nfpm
    pkgs.nxpmicro-mfgtools
    pkgs.vimPlugins.cmp-npm
    pkgs.rPackages.npm
    pkgs.haskellPackages.latest-npm-version
    pkgs.prefetch-npm-deps
    pkgs.nodePackages.npm-merge-driver
    pkgs.npm-check
    pkgs.nodePackages_latest.npm-merge-driver
    pkgs.emacsPackages.npm-mode
    pkgs.npm-check-updates
    pkgs.emacsPackages.npm
    pkgs.nodePackages_latest.npm
    pkgs.nodePackages.npm
    pkgs.kdePackages.libqaccessibilityclient
    pkgs.emacsPackages.emacsql-sqlite-builtin
    pkgs.python312Packages.georss-qld-bushfire-alert-client
    pkgs.python311Packages.georss-qld-bushfire-alert-client
    pkgs.gnomeExtensions.frequency-boost-switch
    pkgs.rPackages.QUBICdata
    pkgs.rPackages.QBAsyDist
    pkgs.haskellPackages.quickcheck-combinators
    pkgs.lxqt.lxqt-build-tools_0_13
    pkgs.lxqt.lxqt-build-tools
    pkgs.quodlibet-without-gst-plugins
    pkgs.sbclPackages.qimageblitz
    pkgs.emacsPackages.quick-buffer-switch
    pkgs.haskellPackages.quickcheck-arbitrary-adt
    pkgs.haskellPackages.quickcheck-arbitrary-template
    pkgs.libsForQt5.qtwebkit
    pkgs.plasma5Packages.qtwebkit
    pkgs.libsForQt5.qtwebkit-plugins
    pkgs.qt5.qtwebkit
    pkgs.sbclPackages.qtwebkit
    pkgs.plasma5Packages.qtwebkit-plugins
    pkgs.rqbit
    pkgs.qt-box-editor
    pkgs.qtbitcointrader
    pkgs.python312Packages.qbittorrent-api
    pkgs.qbittorrent
    pkgs.qbittorrent-nox
    pkgs.python311Packages.qbittorrent-api
    pkgs.qbittorrent-qt5
    pkgs.sbclPackages.metacopy-with-contextl
    pkgs.coqPackages.metacoq
    pkgs.sbclPackages.metabang-bind-test
    pkgs.gnome.metacity
    pkgs.metasploit
    pkgs.metabase
    pkgs.sbclPackages.meta-sexp
    pkgs.metaBuildEnv
    pkgs.ocamlPackages.metadata
    pkgs.python311Packages.metar
    pkgs.sbclPackages.metacopy
    pkgs.sourcehut.metasrht
    pkgs.haskellPackages.meta-misc
    pkgs.sbclPackages.metatilities-test
    pkgs.sbclPackages.metalock
    pkgs.python311Packages.metawear
    pkgs.coqPackages.metacoq-erasure
    pkgs.emacsPackages.metaweblog
    pkgs.coqPackages.metacoq-safechecker
    pkgs.metamorphose2
    pkgs.haskellPackages.metaplug
    pkgs.sbclPackages.metap-test
    pkgs.haskellPackages.metaheuristics
    pkgs.sbclPackages.metatilities
    pkgs.emacsPackages.metal-archives
    pkgs.sbclPackages.meta
    pkgs.rPackages.Rfacebook
    pkgs.rPackages.rfacebookstat
    pkgs.rPackages.facebookadsR
    pkgs.mautrix-facebook
    pkgs.rPackages.facebookleadsR
    pkgs.bitlbee-facebook
    pkgs.haskellPackages.happstack-facebook
    pkgs.pidginPackages.purple-facebook
    pkgs.home-assistant-component-tests.facebook
    pkgs.rPackages.facebookorganicR
    pkgs.haskellPackages.haxl-facebook
    pkgs.haskellPackages.Facebook-Password-Hacker-Online-Latest-Version
    pkgs.python311Packages.facebook-sdk
    pkgs.python312Packages.facebook-sdk
    pkgs.emacsPackages.term+mux
    pkgs.perl538Packages.TermVT102Boundless
    pkgs.python312Packages.simple-term-menu
    pkgs.python311Packages.simple-term-menu
    pkgs.haskellPackages.hs-sdl-term-emulator
    pkgs.haskellPackages.hs-term-emulator
    pkgs.perlPackages.TermVT102Boundless
    pkgs.perl536Packages.TermVT102Boundless
    pkgs.haskellPackages.aterm-utils
    pkgs.ytermusic
    pkgs.emacsPackages.terminal-focus-reporting
    pkgs.haskellPackages.temporal-music-notation-western
    pkgs.haskellPackages.temporal-music-notation
    pkgs.haskellPackages.temporal-music-notation-demo
    pkgs.haskellPackages.terminal-punch
    pkgs.perl538Packages.TermShellUI
    pkgs.perlPackages.TermShellUI
    pkgs.perl536Packages.TermShellUI
    pkgs.terminus_font_ttf
    pkgs.vimPlugins.terminus
    pkgs.emacsPackages.term-run
    pkgs.terminus_font
    pkgs.haskellPackages.tersmu
    pkgs.termius
    pkgs.perl538Packages.TermUI
    pkgs.perlPackages.TermUI
    pkgs.perl536Packages.TermUI
    pkgs.emacsPackages.term+mux
    pkgs.termusic
    pkgs.emacsPackages.term+mux
    pkgs.haskellPackages.free-theorems-counterexamples
    pkgs.python312Packages.types-aiobotocore-license-manager-linux-subscriptions
    pkgs.python311Packages.types-aiobotocore-license-manager-linux-subscriptions
    pkgs.emacsPackages.alert-termux
    pkgs.emacsPackages.term+mux
    pkgs.haskellPackages.iterm-show-JuicyPixels
    pkgs.terraform-providers.aviatrix
    pkgs.terraform-providers.infoblox
    pkgs.rPackages.pd_081229_hg18_promoter_medip_hx1
    pkgs.terraform-providers.lxd
    pkgs.terraform-providers.external
    pkgs.terraform-providers.constellix
    pkgs.terraform-providers.dexidp
    pkgs.terraform-providers.flexibleengine
    pkgs.terraform-providers.proxmox
    pkgs.terraform-providers.linuxbox
    pkgs.gnomeExtensions.cronomix
    pkgs.terraform-providers.yandex
    pkgs.terraform-providers.signalfx
    pkgs.terraform-providers.matchbox
    pkgs.terraform-providers.brightbox
    pkgs.rPackages.featureCorMatrix
    pkgs.terraform-providers.virtualbox
    pkgs.gnomeExtensions.workspace-matrix
    pkgs.terraform-providers.exoscale
    pkgs.terraform-providers.nutanix
    pkgs.terraform-providers.equinix
    pkgs.rPackages.scatterPlotMatrix
    pkgs.sbclPackages.cl-migratum_dot_driver_dot_mixins
    pkgs.rPackages.ThermIndex
    pkgs.rPackages.alabaster_matrix
    pkgs.rPackages.heteromixgm
    pkgs.xdg-terminal-exec
    pkgs.xdg-terminal-exec-mkhl
    pkgs.haskellPackages.terminal-text
    pkgs.rPackages.ggOceanMaps
    pkgs.rPackages.NipponMap
    pkgs.rPackages.diffusionMap
    pkgs.python312Packages.deep-chainmap
    pkgs.rPackages.canadianmaps
    pkgs.rPackages.annmap
    pkgs.python312Packages.chainmap
    pkgs.rPackages.satscanMapper
    pkgs.rPackages.oceanmap
    pkgs.coqPackages.mathcomp-finmap
    pkgs.networkmanagerapplet
    pkgs.haskellPackages.nonemptymap
    pkgs.haskellPackages.nestedmap
    pkgs.haskellPackages.nomyx-api
    pkgs.nomad-pack
    pkgs.notemap
    pkgs.sbclPackages.nkeymaps
    pkgs.python312Packages.netmap
    pkgs.home-assistant-component-tests.nmap_tracker
    pkgs.python312Packages.python-nmap
    pkgs.python311Packages.python-nmap
    pkgs.python311Packages.netmap
    pkgs.rPackages.nmaplateplot
    pkgs.haskellPackages.NMap
    pkgs.python311Packages.nmapthon2
    pkgs.nmapsi4
    pkgs.python312Packages.nmapthon2
    pkgs.nmap-parse
    pkgs.nmap-formatter
    pkgs.nmap
    pkgs.haskellPackages.shh-extras
    pkgs.haskellPackages.syb-extras
    pkgs.su-exec
    pkgs.sbclPackages.sc-extensions
    pkgs.haskellPackages.sr-extra
    pkgs.haskellPackages.s-expression
    pkgs.ocamlPackages.sexp_grammar
    pkgs.python312Packages.sexpdata
    pkgs.sbclPackages.sexml
    pkgs.python311Packages.sexpdata
    pkgs.haskellPackages.sexpresso
    pkgs.haskellPackages.sexp
    pkgs.haskellPackages.sext
    pkgs.haskellPackages.sexp-grammar
    pkgs.ocamlPackages.sexp_macro
    pkgs.haskellPackages.sexp-show
    pkgs.ocamlPackages.sexp_diff
    pkgs.ocamlPackages.sexp_select
    pkgs.ocamlPackages.sexplib0
    pkgs.emacsPackages.sexp-move
    pkgs.haskellPackages.sexpr
    pkgs.emacsPackages.sexy-monochrome-theme
    pkgs.haskellPackages.sexpr-parser
    pkgs.ocamlPackages.sexp
    pkgs.sbclPackages.sexml-objects
    pkgs.ocamlPackages.sexp_pretty
    pkgs.sexpp
    pkgs.ocamlPackages.sexplib
    pkgs.emacsPackages.sexp-diff
    pkgs.python312Packages.nose-warnings-filters
    pkgs.python311Packages.nose-warnings-filters
    pkgs.sbclPackages.cl-glfw-opengl-sun__triangle__list
    pkgs.sbclPackages.cl-glfw-opengl-ingr__blend__func__separate
    pkgs.pantheon.wingpanel-applications-menu
    pkgs.sbclPackages.aws-sign4-example
    pkgs.rPackages.WeightedCluster
    pkgs.sbclPackages.cl-glfw-opengl-sgix__igloo__interface
    pkgs.pantheon.wingpanel-indicator-power
    pkgs.wyoming-satellite
    pkgs.pantheon.wingpanel-indicator-datetime
    pkgs.pantheon.wingpanel-indicator-bluetooth
    pkgs.haskellPackages.aviation-weight-balance
    pkgs.haskellPackages.aviation-cessna172-weight-balance
    pkgs.pantheon.wingpanel-indicator-keyboard
    pkgs.pantheon.wingpanel-indicator-network
    pkgs.pantheon.wingpanel-indicator-session
    pkgs.haskellPackages.webfinger-client
    pkgs.rPackages.WeightedEnsemble
    pkgs.haskellPackages.netwire-vinylglfw-examples
    pkgs.fftwSinglePrec
    pkgs.wooting-udev-rules
    pkgs.fftwFloat
    pkgs.python311Packages.wasmer-compiler-singlepass
    pkgs.python312Packages.wasmer-compiler-singlepass
    pkgs.haskellPackages.wreq-stringless
    pkgs.gnomeExtensions.wiggle
    pkgs.rPackages.wiggleplotr
    pkgs.haskellPackages.wigner-ville-accelerate
    pkgs.wiggle
    pkgs.api-linter
    pkgs.haskellPackages.apiary-memcached
    pkgs.apitrace
    pkgs.python312Packages.apipkg
    pkgs.emacsPackages.apiwrap
    pkgs.haskellPackages.api-opentheory-unicode
    pkgs.haskellPackages.api-monobank
    pkgs.haskellPackages.api-maker
    pkgs.haskellPackages.apigen
    pkgs.haskellPackages.apiary-persistent
    pkgs.haskellPackages.apiary
    pkgs.haskellPackages.api-rpc-accumulate
    pkgs.haskellPackages.apiary-logger
    pkgs.haskellPackages.apiary-purescript
    pkgs.haskellPackages.api-field-json-th
    pkgs.haskellPackages.api-rpc-pegnet
    pkgs.haskellPackages.apiary-websockets
    pkgs.python312Packages.apischema
    pkgs.haskellPackages.apiary-authenticate
    pkgs.python312Packages.apispec
    pkgs.haskellPackages.apiary-eventsource
    pkgs.apio
    pkgs.haskellPackages.api-tools
    pkgs.haskellPackages.apiary-redis
    pkgs.haskellPackages.apis
    pkgs.python311Packages.apispec-webframeworks
    pkgs.haskellPackages.apiary-http-client
    pkgs.haskellPackages.api-yoti
    pkgs.haskellPackages.apiary-helics
    pkgs.haskellPackages.apiary-mongoDB
    pkgs.python311Packages.pdb2pqr
    pkgs.patch2pr
    pkgs.rPackages.gep2pep
    pkgs.rPackages.pts2polys
    pkgs.cp210x-program
    pkgs.rPackages.Path2PPI
    pkgs.haskellPackages.http2-grpc-proto3-wire
    pkgs.haskellPackages.http2-grpc-proto-lens
    pkgs.rPackages.pwr2ppl
    pkgs.texlivePackages.ps2eps
    pkgs.haskellPackages.hp2pretty
    pkgs.haskellPackages.ip2proxy
    pkgs.go-libp2p-daemon
    pkgs.hp2p
    pkgs.ps2eps
    pkgs.rPackages.ip2proxy
    pkgs.passphrase2pgp
    pkgs.polylux2pdfpc
    pkgs.texlivePackages.ptex2pdf
    pkgs.haskellPackages.prof2pretty
    pkgs.haskellPackages.pipes-p2p-examples
    pkgs.haskellPackages.distributed-process-p2p
    pkgs.python312Packages.pdb2pqr
    pkgs.haskellPackages.pipes-p2p
    pkgs.texlivePackages.pst2pdf
    pkgs.pdb2pqr
    pkgs.texlivePackages.ps2pk
    pkgs.p2pvc
    pkgs.p2pool
    pkgs.python312Packages.show-in-file-manager
    pkgs.pandoc-drawio-filter
    pkgs.home-assistant-component-tests.wiffi
    pkgs.python311Packages.openevsewifi
    pkgs.ifwifi
    pkgs.raspberrypiWirelessFirmware
    pkgs.python312Packages.openevsewifi
    pkgs.fishPlugins.wakatime-fish
    pkgs.haskellPackages.wai-app-file-cgi
    pkgs.haskellPackages.wilton-ffi
    pkgs.vimPlugins.wiki-ft-vim
    pkgs.rictydiminished-with-firacode
    pkgs.iosevka-comfy.comfy-wide-fixed
    pkgs.gnomeExtensions.wifi-qrcode
    pkgs.python312Packages.python-wifi
    pkgs.vimPlugins.wildfire-vim
    pkgs.gnomeExtensions.wifi-switcher
    pkgs.python312Packages.anova-wifi
    pkgs.python311Packages.python-wifi
    pkgs.home-assistant-component-tests.google_wifi
    pkgs.linux-wifi-hotspot
    pkgs.python311Packages.anova-wifi
    pkgs.asahi-wifisync
    pkgs.python311Packages.wiffi
    pkgs.python312Packages.wiffi
    pkgs.wifite2
    pkgs.wifi-qr
    pkgs.wifish
    pkgs.python312Packages.wifi
    pkgs.python311Packages.wifi
    pkgs.rPackages.adbcsqlite
    pkgs.aspellDicts.bg
    pkgs.aspellDicts.br
    pkgs.python312Packages.pure-python-adb
    pkgs.rPackages.adbcdrivermanager
    pkgs.haskellPackages.anydbm
    pkgs.python311Packages.pure-python-adb-homeassistant
    pkgs.python312Packages.pure-python-adb-homeassistant
    pkgs.amd-blis
    pkgs.haskellPackages.adobe-swatch-exchange
    pkgs.rPackages.adbcpostgresql
    pkgs.python311Packages.pure-python-adb
    pkgs.rPackages.adbi
    pkgs.python312Packages.agate-dbf
    pkgs.adapta-backgrounds
    pkgs.python311Packages.agate-dbf
    pkgs.python311Packages.adblock
    pkgs.python311Packages.adb-shell
    pkgs.adbtuifm
    pkgs.adb-sync
    pkgs.python312Packages.adb-enhanced
    pkgs.haskellPackages.adblock2privoxy
    pkgs.python311Packages.adb-homeassistant
    pkgs.python312Packages.adblock
    pkgs.adbfs-rootless
    pkgs.python312Packages.adb-homeassistant
    pkgs.python311Packages.adb-enhanced
    pkgs.python312Packages.adb-shell
    pkgs.haskellPackages.adb
    pkgs.bpp-seq
    pkgs.haskellPackages.bindings-yices
    pkgs.bosun
    pkgs.boxbuddy
    pkgs.haskellPackages.boltzmann-brain
    pkgs.linuxPackages_6_6_hardened.bpftrace
    pkgs.python312Packages.bugsnag
    pkgs.ocamlPackages.bheap
    pkgs.bibtool
    pkgs.linuxPackages_6_1_hardened.bbswitch
    pkgs.btar
    pkgs.haskellPackages.base-compat
    pkgs.bonsai
    pkgs.ballerina
    pkgs.libsForQt5.bluedevil
    pkgs.python311Packages.beaker
    pkgs.haskellPackages.bv-little
    pkgs.python311Packages.bitarray
    pkgs.python312Packages.boolean-py
    pkgs.baboossh
    pkgs.haskellPackages.bitwise-enum
    pkgs.benchexec
    pkgs.prometheus-bitcoin-exporter
    pkgs.sbclPackages.buildnode-test
    pkgs.luajitPackages.busted
    pkgs.python312Packages.bravado-core
    pkgs.haskellPackages.base64-string
    pkgs.haskellPackages.connections
    pkgs.sbclPackages.cl-launch
    pkgs.python312Packages.commandparse
    pkgs.azure-cli-extensions.change-analysis
    pkgs.sbclPackages.cl-glfw-opengl-nv__gpu__program4
    pkgs.sbclPackages.cl-mtgnet-sync
    pkgs.lua51Packages.cldr
    pkgs.cozette
    pkgs.python312Packages.cock
    pkgs.nodePackages_latest.coc-jest
    pkgs.sbclPackages.cl-glfw-opengl-intel__parallel__arrays
    pkgs.emacsPackages.company-org-block
    pkgs.chainsaw
    pkgs.sbclPackages.cl-scram
    pkgs.sbclPackages.cl-cuda-examples
    pkgs.haskellPackages.coerce-util
    pkgs.python311Packages.crccheck
    pkgs.haskellPackages.chan
    pkgs.sbclPackages.cl_plus_ssl
    pkgs.connman-gtk
    pkgs.emacsPackages.clean-buffers
    pkgs.chain-bench
    pkgs.darwin.binutilsDualAs
    pkgs.sbclPackages.cl-etcd
    pkgs.haskellPackages.cache-polysemy
    pkgs.sbclPackages.cl-glfw-opengl-sgix__scalebias__hint
    pkgs.haskellPackages.currency
    pkgs.celeste
    pkgs.sbclPackages.cl-ana_dot_pathname-utils
    pkgs.sbclPackages.cleric-test
    pkgs.haskellPackages.avro-piper
    pkgs.haskellPackages.aos-signature
    pkgs.python311Packages.avro
    pkgs.adoptopenjdk-jre-openj9-bin-11
    pkgs.ocamlPackages.async_kernel
    pkgs.haskellPackages.aws
    pkgs.gnomeExtensions.argos
    pkgs.haskellPackages.audiovisual
    pkgs.python311Packages.autopage
    pkgs.abcmidi
    pkgs.amdgpu_top
    pkgs.python312Packages.auditok
    pkgs.python312Packages.aiosenz
    pkgs.atanks
    pkgs.python311Packages.amply
    pkgs.haskellPackages.amazonka-network-firewall
    pkgs.vimPlugins.auto-save-nvim
    pkgs.asterisk_20
    pkgs.arpa2cm
    pkgs.haskellPackages.adjunction
    pkgs.python312Packages.aiodiscover
    pkgs.amazon-ec2-utils
    pkgs.haskellPackages.amazonka-appmesh
    pkgs.ocamlPackages.alcotest-mirage
    pkgs.haskellPackages.aws-sdk-xml-unordered
    pkgs.arcanist
    pkgs.emacsPackages.a
    pkgs.img2pdf
    pkgs.rubyPackages_3_2.rb-inotify
    pkgs.python311Packages.rfc3987
    pkgs.rPackages.robfilter
    pkgs.haskellPackages.flow-er
    pkgs.rPackages.bbsBayes
    pkgs.python312Packages.overpy
    pkgs.haskellPackages.bytestring-arbitrary
    pkgs.rPackages.firebase
    pkgs.python311Packages.robotframework-excellib
    pkgs.emacsPackages.ansible-vault
    pkgs.python311Packages.pytest-forked
    pkgs.gnomeExtensions.kimpanel
    pkgs.perlPackages.TestCPANMeta
    pkgs.linuxPackages_xanmod_latest.nvidia_x11_vulkan_beta
    pkgs.emacsPackages.gnuplot-mode
    pkgs.haskellPackages.pipes-attoparsec
    pkgs.rPackages.stemmatology
    pkgs.python312Packages.pytestCheckHook
    pkgs.rPackages.Density_T_HoldOut
    pkgs.rPackages.MEDITS
    pkgs.python312Packages.xstatic-font-awesome
    pkgs.rPackages.verhoeff
    pkgs.rPackages.MadanTextNetwork
    pkgs.haskellPackages.options-time
    pkgs.perlPackages.HTMLFormatExternal
    pkgs.haskellPackages.smallstring
    pkgs.python311Packages.mkdocs
    pkgs.haskellPackages.SMTPClient
    pkgs.rPackages.camcorder
    pkgs.cowsay
  ];
}